name: build-app
run-name: build app from the ${{ github.head_ref }} branch
on: pull_request
jobs:
  build-woof-target:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/build-ios-simulator.sh
